### ISSUE TITLE
I have a problem whenever I am adding the pruned model path.? Is there any problem on the .pt problem? how can I solve it?

### ISSUE THREAD

**Issue by Ayanzadeh93** [lmbxmu/ABCPruner#2]
Hello, I have a problem whenever I am adding the pruned model path.? Is there any problem on the .pt problem(--honey.model) argument)? how can I solve it?

Traceback (most recent call last):
  File "bee_cifar.py", line 54, in <module>
    raise ('Honey_model path should be exist!')
TypeError: exceptions must derive from BaseException

**Comment by lmbxmu** [comment]
Show me your command please.
